# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_import_packing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_list', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='import',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PackingList'),
        ),
    ]
