# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161210_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
