# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_packinglist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='date',
            field=models.DateField(),
        ),
    ]
