# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161211_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packinglist',
            old_name='packing_list',
            new_name='name',
        ),
    ]
