# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161211_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('art', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article')),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PackingList')),
            ],
        ),
        migrations.AlterField(
            model_name='import',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
