# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161211_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fabric',
            field=models.IntegerField(),
        ),
    ]
