# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161213_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
